-- Insert sample mobile phones
INSERT INTO mobile_products (
  name,
  brand,
  price,
  display_specs,
  processor,
  ram,
  storage,
  battery,
  camera,
  chipset,
  charging_specs,
  resolution,
  screen_size,
  color,
  os,
  image_url,
  announced,
  status,
  display_type,
  display_protection,
  dimensions,
  weight,
  build_material,
  sim_type,
  wlan,
  bluetooth,
  nfc,
  gps,
  usb_type,
  network_technology,
  network_speed,
  sensors,
  available_colors
) VALUES
(
  'OnePlus 12',
  'OnePlus',
  69999.00,
  'LTPO AMOLED, 120Hz, Dolby Vision',
  'Snapdragon 8 Gen 3',
  '12GB',
  '256GB',
  '5400 mAh',
  '50MP + 48MP + 64MP',
  'Snapdragon 8 Gen 3',
  '100W SUPERVOOC',
  '1440 x 3168 pixels',
  '6.82 inches',
  'Flowy Emerald',
  'Android 14, OxygenOS 14',
  'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/oneplus12.webp',
  'January 2024',
  'Available',
  'LTPO AMOLED',
  'Gorilla Glass Victus 2',
  '164.3 x 75.8 x 9.2 mm',
  '220 g',
  'Glass front (Gorilla Glass Victus 2), glass back, aluminum frame',
  'Dual SIM (Nano-SIM, dual stand-by)',
  'Wi-Fi 802.11 a/b/g/n/ac/6e/7, tri-band',
  '5.3, A2DP, LE',
  true,
  'GPS, GLONASS, BDS, GALILEO',
  'USB Type-C 3.2',
  'GSM / HSPA / LTE / 5G',
  'HSPA 42.2/5.76 Mbps, LTE-A, 5G',
  ARRAY['Fingerprint (under display, optical)', 'accelerometer', 'gyro', 'proximity', 'compass'],
  ARRAY['Flowy Emerald', 'Silky Black']
),
(
  'Nothing Phone (2)',
  'Nothing',
  44999.00,
  'LTPO OLED, 120Hz, HDR10+',
  'Snapdragon 8+ Gen 1',
  '12GB',
  '256GB',
  '4700 mAh',
  '50MP + 50MP',
  'Snapdragon 8+ Gen 1',
  '45W Fast Charging',
  '1080 x 2412 pixels',
  '6.7 inches',
  'White',
  'Android 13, Nothing OS 2.0',
  'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/nothingphone2.webp',
  'July 2023',
  'Available',
  'LTPO OLED',
  'Gorilla Glass 5',
  '162.1 x 76.4 x 8.6 mm',
  '201.2 g',
  'Glass front (Gorilla Glass), glass back (Gorilla Glass), aluminum frame',
  'Dual SIM (Nano-SIM, dual stand-by)',
  'Wi-Fi 802.11 a/b/g/n/ac/6',
  '5.3, A2DP, LE',
  true,
  'GPS, GLONASS, BDS, GALILEO, QZSS',
  'USB Type-C 2.0',
  'GSM / HSPA / LTE / 5G',
  'HSPA 42.2/5.76 Mbps, LTE-A, 5G',
  ARRAY['Fingerprint (under display, optical)', 'accelerometer', 'gyro', 'proximity', 'compass'],
  ARRAY['White', 'Dark Gray']
);

-- Insert sample laptops
INSERT INTO laptops (
  name,
  brand,
  price,
  display_specs,
  processor,
  ram,
  storage,
  battery,
  graphics,
  ports,
  color,
  os,
  image_url,
  connectivity_specs,
  performance_specs
) VALUES
(
  'ROG Zephyrus G14 (2024)',
  'ASUS',
  174990.00,
  '14-inch ROG Nebula HDR Mini LED (2880 x 1800)',
  'AMD Ryzen 9 8945HS',
  '32GB DDR5',
  '1TB PCIe 4.0 NVMe SSD',
  '76WHrs',
  'NVIDIA GeForce RTX 4070 8GB GDDR6',
  '2x USB 4.0, 2x USB 3.2 Gen 2 Type-A, HDMI 2.1, 3.5mm Combo Audio Jack',
  'Eclipse Gray',
  'Windows 11 Pro',
  'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/zephyrusg14.webp',
  jsonb_build_object(
    'wifi', 'Wi-Fi 6E',
    'bluetooth', '5.3',
    'webcam', '1080p IR Camera'
  ),
  jsonb_build_object(
    'cpu_cores', '8 cores, 16 threads',
    'gpu_memory', '8GB GDDR6',
    'memory_type', 'DDR5-5600'
  )
),
(
  'Lenovo Yoga 9i (2024)',
  'Lenovo',
  149990.00,
  '14-inch 4K OLED Touch (3840 x 2400)',
  'Intel Core Ultra 7 155H',
  '16GB LPDDR5X',
  '1TB PCIe Gen 4 SSD',
  '75Wh',
  'Intel Arc Graphics',
  'Thunderbolt 4, USB Type-A, USB Type-C, Audio jack',
  'Oatmeal',
  'Windows 11 Home',
  'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/yoga9i.webp',
  jsonb_build_object(
    'wifi', 'Wi-Fi 6E',
    'bluetooth', '5.3',
    'webcam', '1080p with IR'
  ),
  jsonb_build_object(
    'cpu_cores', '16 cores (6P + 8E + 2LP-E)',
    'gpu_features', 'XeSS, Ray Tracing',
    'memory_type', 'LPDDR5X-7467'
  )
);