// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://luzopqvwwmxrtcibsmjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1em9wcXZ3d214cnRjaWJzbWp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY0MTcyNjQsImV4cCI6MjA1MTk5MzI2NH0.X37kj_onfpoENktxs5pXlJjpCVXTLu0jm6FN1MQCcy0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);